version: '3.3'

services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./:/app:rw
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped
    networks:
      - goldenhands
    env_file:
      - .env

  nginx:
    image: nginx:1.18-alpine
    volumes:
      - ./docker/nginx:/etc/nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - goldenhands

  front:
    build:
      dockerfile: ./docker/front/Dockerfile
      context: .
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - goldenhands

  db:
    image: postgres:14.2-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - goldenhands
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: goldenhands

networks:
  goldenhands:

volumes:
  db-data:
  redis-data:
  node_modules:
