version: '3.3'

services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./:/app:rw
    restart: always
    networks:
      - goldenhands
    env_file:
      - .env

  nginx:
    image: nginx:1.18-alpine
    volumes:
      - ./docker/nginx:/etc/nginx
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - goldenhands

  front:
    build:
      dockerfile: ./docker/front/Dockerfile
      context: .
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    restart: always
    networks:
      - goldenhands

networks:
  goldenhands:

volumes:
  node_modules:
